name: Sync labels
on:
  # You can run this with every type of event, but it's better to run it only when you actually need it.
  workflow_dispatch:

permissions: {} # Set permissions at the job level.

jobs:
  labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      # Ref: https://github.com/EndBug/label-sync
      - uses: EndBug/label-sync@v2
        with:
          config-file: https://raw.githubusercontent.com/rdmorganiser/.github/main/.github/labels.yml
          # If you want to delete any additional label, set this to true
          delete-other-labels: false
